const Data = [
  {
    image: "../assets/img/ManOfSteel.jpg",
    tittle: "Man Of Steel",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 5,
  },
  {
    image: "../assets/img/Deadpool.jpg",
    tittle: "Deadpool",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 3,
  },
  {
    image: "../assets/img/Avengers.png",
    tittle: "Avengers",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 4,
  },
  {
    image: "../assets/img/Batman.jpg",
    tittle: "Batman",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 5,
  },
  {
    image: "../assets/img/Extraction.jpg",
    tittle: "Extraction",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 2,
  },
  {
    image: "../assets/img/Transformer.jpg",
    tittle: "Transformer",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 5,
  },
  {
    image: "../assets/img/NinjaTurtle.jpg",
    tittle: "Ninja Turtle",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 5,
  },
  {
    image: "../assets/img/Power Ranger.jpg",
    tittle: "Power Ranger",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 5,
  },
  {
    image: "../assets/img/Birds Of Prey.jpg",
    tittle: "Birds Of Prey",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 3,
  },
  {
    image: "../assets/img/pirates.jpg",
    tittle: "Pirates",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 5,
  },
  {
    image: "../assets/img/GodZilla.jpg",
    tittle: "GodZilla",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 3,
  },
  {
    image: "../assets/img/Baby Driver.jpg",
    tittle: "Baby Driver",
    descrption: "Actions, Thriller, Comedy",
    descrption: "this is a greats movie",
    rating: 5,
  },
];
export default Data;
